--run script to setup database and tables

CREATE DATABASE Stepful;

CREATE TABLE Coach (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(255) NOT NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)

CREATE TABLE Student (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(255) NOT NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)

CREATE TABLE Slot (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    startTime DATETIME NOT NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
)

CREATE TABLE CoachHasSlot (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    coachId INT NOT NULL,
    slotId INT NOT NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (coachId) REFERENCES Coach(id),
    FOREIGN KEY (slotId) REFERENCES Slot(id)
)

CREATE TABLE StudentBooksSlot (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    studentId INT NOT NULL,
    slotId INT NOT NULL,
    satisfactionScore INT,
    note TEXT,

    FOREIGN KEY (studentId) REFERENCES Student(id),
    FOREIGN KEY (slotId) REFERENCES Slot(id)
)
